### PR TITLE
add Social Hrs, my 1st quarto commit

### PR DESCRIPTION
**Pull request by stefaniebutland**

### CODE REVIEW

**Comment by stefaniebutland** [comment]
How do I add internal link to Seaside Chats, etc. Social Hours from Post-cohort followup?

I see [Quarto crossrefs](https://quarto.org/docs/books/book-crossrefs.html) example below, but need info on current crossrefs in Approach Guide.

```
# Introduction {#sec-introduction}

See @sec-introduction for additional discussion.
```

**Comment by jules32** [comment]
Wooo @stefaniebutland first quarto commit! 🥳 

And great questions. 

**Question 1:** Quarto cross-refs work with books but not sites (and our approach guide is technically a site, not a book). With sites, we can instead do `[linked text](pre-cohort-engage.qmd#planning-document)` -> and note that we can link to `.qmd` instead of `.html` which will preserve the linking whether it turns out as html or pdf. 

**Question 2:** Quarto can combine many file types: `.qmd`, `.md`, `.Rmd`, `.ipynb`. I have been experimenting with just plain 'ol `.md` with chapters that don't have code. Which in this book, is currently all of them. GitHub displays `.md` files, but not (yet) `.qmd` files, so that's one reason I've done a lot of `.md` ones. But powerful that quarto makes them so interoperable.

**Comment by jules32** [comment]
I'll delete the branch too but we can discuss further if that's not a convention you use

**Review by jules32 — COMMENTED** [review]
The review is approved! This would be a great thing to talk about in a co-working session too, I would love to learn your approach to GitHub reviews

**Comment by stefaniebutland** [comment]
Opened an issue for mutual GitHub reviews skillshare https://github.com/Openscapes/how_we_work/issues/152

**Pull request merged**
